Implement commons
EternalCodeTeam/ParcelLockers pull request #107
Opened 2024-09-29 13:13 UTC by Jakubk15

2024-09-29 13:44 UTC, Rollczi approved these changes

2024-09-29 14:06 UTC, P1otrulla submitted a review, later dismissed

2024-09-29 14:14 UTC, vLuckyyy requested changes
We also have ItemUtil and Duration formatter in eternalcode-commons

2024-09-29 14:14 UTC, vLuckyyy commented on .github/CODEOWNERS
unrelated

2024-09-30 17:19 UTC, igoyek submitted a review, later dismissed

2024-10-01 16:57 UTC, Jakubk15 commented
> We also have ItemUtil and Duration formatter in eternalcode-commons

Sadly the ItemUtil has a different behavior than the one I intend to use, so I will stick to mine for the time being. Currently there is no need for implementing the DurationParser, but thanks 😅

2024-10-01 17:17 UTC, merged